
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/team02-m23-10am-4
owner: ucsb-cs156-m23
repo_name: team02-m23-10am-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjU2MDYwNjY0","is_bot":false,"login":"publicqi","name":""},"headRefName":"Qi-MenuItemReviewAll","number":48,"title":"qs - add controller and tests for MenuItemReview","url":"https://github.com/ucsb-cs156-m23/team02-m23-10am-4/pull/48"},{"author":{"id":"MDQ6VXNlcjU2MDYwNjY0","is_bot":false,"login":"publicqi","name":""},"headRefName":"Qi-MenuItemReviewTable","number":47,"title":"qs - add Entity and Repository for MenuItemReview","url":"https://github.com/ucsb-cs156-m23/team02-m23-10am-4/pull/47"},{"author":{"id":"MDQ6VXNlcjIwODAwNjI5","is_bot":false,"login":"MPriston","name":"Matt Priston"},"headRefName":"Matt-Articles-Delete","number":44,"title":"MP - Added DELETE endpoint to Articles","url":"https://github.com/ucsb-cs156-m23/team02-m23-10am-4/pull/44"}]
