
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/team02-m23-10am-4
owner: ucsb-cs156-m23
repo_name: team02-m23-10am-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjE4Njg1MDcy","is_bot":false,"login":"iain801","name":"Iain Weissburg"},"headRefName":"iain801-patch-1","number":43,"title":"iw - Update README.md instructions link","url":"https://github.com/ucsb-cs156-m23/team02-m23-10am-4/pull/43"},{"author":{"id":"MDQ6VXNlcjE4Njg1MDcy","is_bot":false,"login":"iain801","name":"Iain Weissburg"},"headRefName":"Iain-HelpRequestDelete","number":42,"title":"iw - Iain help request delete","url":"https://github.com/ucsb-cs156-m23/team02-m23-10am-4/pull/42"},{"author":{"id":"MDQ6VXNlcjE4Njg1MDcy","is_bot":false,"login":"iain801","name":"Iain Weissburg"},"headRefName":"Iain-HelpRequestController","number":41,"title":"iw - HelpRequest Controller and Tests","url":"https://github.com/ucsb-cs156-m23/team02-m23-10am-4/pull/41"}]
