
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/team02-m23-10am-4
owner: ucsb-cs156-m23
repo_name: team02-m23-10am-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjIwODAwNjI5","is_bot":false,"login":"MPriston","name":"Matt Priston"},"headRefName":"Matt-MenuItem","number":57,"title":"MP - Added UCSBDiningCommonMenuItem API","url":"https://github.com/ucsb-cs156-m23/team02-m23-10am-4/pull/57"},{"author":{"id":"MDQ6VXNlcjQxMTY1MjA0","is_bot":false,"login":"dscpsyl","name":"SimYouLater"},"headRefName":"ImportFixes","number":56,"title":"DS - FIX: Removed unused imports","url":"https://github.com/ucsb-cs156-m23/team02-m23-10am-4/pull/56"}]
